teleop_twist_joy_node:
  ros__parameters:

    require_enable_button: true

    enable_button: 10
    enable_turbo_button: 4

    axis_linear:
      x: 3
      y: 1

    scale_linear:
      x: 2.5
      y: 2.5

    scale_linear_turbo:
      x: 4.5
      y: 4.5

    axis_angular:
      yaw: 0

    scale_angular:
      yaw: 6.0

    scale_angular_turbo:
      yaw: 8.0